completed tasks
dhbw-ma-ppp/ppp-2024 pull request #10
Opened 2024-10-15 16:41 UTC by laraasphh

2024-10-16 12:03 UTC, PixelWelt requested changes
please remove .DS_Store files from commit

2024-10-16 12:03 UTC, PixelWelt commented on Exercises/.DS_Store
please upload just the exercise file

2024-10-16 12:03 UTC, PixelWelt commented on .DS_Store
please upload just the exercise file

2024-10-16 12:03 UTC, PixelWelt commented on Exercises/LaraBachmann/exercises_01.py
> +y = a/b
this is not integer division use // instead

2024-10-16 12:03 UTC, PixelWelt commented on Exercises/LaraBachmann/exercises_01.py
> +print(f'The temperature {t_fahrenheit} Fahrenheit amounts {t_celsius} °C.')
f strings! Great!

2024-10-16 12:03 UTC, PixelWelt commented on Exercises/LaraBachmann/exercises_01.py
> +print(f'The string occurs {klammer1} x "(" and {klammer2} x ")", which means there are {klammer1 - klammer2} more "(" than ")".')
nice solution to print both counters

2024-10-16 12:59 UTC, laraasphh commented on .DS_Store
Bin erstmal froh, dass ich's geschafft habe es hochzuladen, versuche es dann beim nächsten Mal zu berücksichtigen. Danke dir!

2024-10-16 12:59 UTC, laraasphh commented on Exercises/LaraBachmann/exercises_01.py
> +y = a/b
Ahh sehe es gerade, danke fürs Aufmerksam machen

2024-10-16 13:12 UTC, PixelWelt approved these changes

2024-10-19 14:04 UTC, tisisvince approved these changes

2024-10-19 14:04 UTC, tisisvince commented on Exercises/LaraBachmann/exercises_01.py
> +z = a%b
Consider using more explicit/unique variable names

2024-10-22 15:30 UTC, merged