Excersie01 Vicent Wieg
dhbw-ma-ppp/ppp-2024 pull request #12
Opened 2024-10-15 19:48 UTC by tisisvince

2024-10-16 09:33 UTC, PixelWelt requested changes
Bitte nutze die Python Funktionen, um unnötige Loops zu entfernen.

2024-10-16 09:33 UTC, PixelWelt commented on Exercises/VincentWieg/exercises_01.py
> +print("quotient:", quotient, ", remainder:", remainder)
f strings sind schöner

2024-10-16 09:33 UTC, PixelWelt commented on Exercises/VincentWieg/exercises_01.py
> +print("quotient:", quotient, ", remainder:", remainder)
(f'quotient: {quotient} remainder: {remainder}')

2024-10-16 09:33 UTC, PixelWelt commented on Exercises/VincentWieg/exercises_01.py
> +print("common elements:", common_elements)
Schau dir mal sets und intersections an. Das geht besser und einfacher.

2024-10-16 09:33 UTC, PixelWelt commented on Exercises/VincentWieg/exercises_01.py
> +      aInFirstList += 1
schau dir mal count an. Nach Clean Code würde ich, wenn ich das nicht mit count löse sondern mit einer schleife in eine wiederaufrufbare Funktion packen

2024-10-16 09:37 UTC, PixelWelt commented on Exercises/VincentWieg/exercises_01.py
> +      aInFirstList += 1
nutz DRY und KISS
Don't repeat yourself
Keep it stupid simple

2024-10-16 17:11 UTC, atrejut commented on Exercises/VincentWieg/exercises_01.py
> +print("quotient:", quotient, ", remainder:", remainder)
even shorter: 
```
print(f'{quotient=}, {remainder=}')
```

2024-10-19 07:37 UTC, Adrian410 commented on Exercises/VincentWieg/exercises_01.py
> +print("remainder:", remainder)
Am besten einen f-String verwenden, damit längere print-Anweisung übersichtlich bleiben.

2024-10-19 07:37 UTC, Adrian410 commented on Exercises/VincentWieg/exercises_01.py
> +difBrackets = openCount-closeCount
Es hält deinen Code übersichtlich für jeden Schritt eine Variable anzulegen, jedoch würde ich im hinblick auf Größere Projekte auf openCount und closeCount verzichten. Diese sorgen für zusätzliche Codezeilen, die nicht unbedingt nötig sind.

2024-10-21 19:20 UTC, Saiki77 commented on Exercises/VincentWieg/exercises_01.py
> +print("Temp in cel:", cel)
You could calculate the temperature in the line with the {} brackets. Also You could add "C°" after cel to show the change to metric.

2024-10-21 19:20 UTC, Saiki77 commented on Exercises/VincentWieg/exercises_01.py
> +print("Number of As in first list:", letter_count(first_list, "a"), ", Number of As in second list:", letter_count(second_list, "a"))
Nice output, maybe you could use an f string to keep it more organised without the (,), you also used it in the beginning, so this would keep it stylistically coherent.

2024-10-25 15:48 UTC, atrejut commented
@PixelWelt You requested changes for this PR. Could you take a look whether your comments were addressed and approve if appropriate?
@tisisvince Please merge the PR once you get an approval

2024-10-25 18:06 UTC, PixelWelt approved these changes

2024-10-29 11:15 UTC, PixelWelt requested changes
please dont remove the exercise and just use one folder

2024-10-29 11:19 UTC, PixelWelt approved these changes

2024-10-29 11:20 UTC, merged