Add files via upload
dhbw-ma-ppp/ppp-2024 pull request #13
Opened 2024-10-16 17:55 UTC by itsNerdyBirdy

uploaded exercise01

2024-10-16 18:46 UTC, PixelWelt requested changes
Biite nur den letzten Kommentar ändern Rest ist kein need

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +# (F − 32) ÷ 1,8 = C Umrechnungsformel Fahrenheit zu Celsius
schön, dass du mit einem Kommentar die Umrechnungsformel einsetzt

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +print((t_fahrenheit - 32) /1.8, "\n")
ist das beabsichtigt mit dem linebreak? Print macht nach jedem Statement automatisch eine neue Zeile. 

eine Variable vorher und dann ein f string der dann erklärt was das für eine Zahl ist wäre noch schick

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +print("Es sind",input_string.count('(') - input_string.count(')'), "'(' mehr als ')' vertreten in diesem String \n")
hier wäre es auch nochmal minimal lesbarer mit einem f string 

f'{variablenname} normaer Text' <- Inline Variablen im Print Statement oder in strings generell

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +print("in der ersten Liste sind", len(first_list), "und in der zweiten Liste sind", len(second_list), "Elemente enthalten \n")
s. oben wegen f strings

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +gemeinsammeElemente = set(first_list) & set(second_list)
mag den & operator hier

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +print("Die Listen enthalten", len(gemeinsammeElemente),"gemeinsamme Elemente, diese sind", gemeinsammeElemente, "\n")
s. oben wegen f strings

2024-10-16 18:46 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +print(sum(x.count("a") for x in first_list if "a" in x) + sum(x.count("a") for x in second_list if "a" in x))
ich hasse diese Zeile Code. 
Bitte teile das in mehr Zeilen auf, damit es lesbarer wird. 

Außerdem kannst du die liste einfach in einen string verwandeln und dann count auf den string andwenden ohne zu loopen.

Laut Aufgabe soll nicht die Summe der a's in den Strings geprinted werden sondern jeweils pro Liste.

2024-10-17 09:13 UTC, itsNerdyBirdy commented on KiraWildeexercises_01.py
> +print((t_fahrenheit - 32) /1.8, "\n")
linebreak ist beabsichtigt, ich fand so kann man die Aufgaben in der Ausgabe besser auseinander halten.

2024-10-17 09:16 UTC, itsNerdyBirdy commented on KiraWildeexercises_01.py
> +gemeinsammeElemente = set(first_list) & set(second_list)
siehst du denn Probleme die der "&" Operator erzeugen könnte?

2024-10-17 09:57 UTC, PixelWelt commented on KiraWildeexercises_01.py
> +gemeinsammeElemente = set(first_list) & set(second_list)
Ich mag ihn. Habe selber mit intersections gearbeitet und finde die & lösung gut

2024-10-17 11:05 UTC, PixelWelt requested changes
Pleased Upload Just one File. There ist one in the Home directory of the repo and one in your exercise folder.

2024-10-17 12:33 UTC, PixelWelt approved these changes

2024-10-17 12:33 UTC, PixelWelt commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +#// Rundet das Ergebnis auf eine Ganzzahl & % ist das Modolo Zeichen, welches den Rest einer Rechenoperation ausgibt
You can use divmod() to Output Quotient and Modulo in one operation

2024-10-17 12:33 UTC, PixelWelt commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +print(f"{t_fahrenheit} Grat Fahrenheit umgerechnet in Clesius sind {t_celsius} Grat Celsius", "\n")
Typo Grad.
Nice f String use

2024-10-17 12:33 UTC, PixelWelt commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +anzahlAInListeZwei = ''.join(first_list).count("a") #anzahlAInListeZwei = int
Nice

2024-10-21 16:41 UTC, FabianPerl93 reviewed
I especially liked the solutions for ecercise 5 and 6.

2024-10-21 16:41 UTC, FabianPerl93 commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +print ("2711274328912 : 23369245575 =", 2711274328912//23369245575, "\n", "Der Rest ist: ", 2711274328912 % 23369245575, "\n")
You don´t have to use the newline character at the end of the print-statement. Each statement is printed in a new line automatically.

2024-10-21 16:41 UTC, FabianPerl93 commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +anzahlAInListeZwei = ''.join(first_list).count("a") #anzahlAInListeZwei = int
I really like this solution to the problem.

2024-10-21 16:58 UTC, LinusL2005 commented on Exercises/KiraWilde/KiraWildeexercises_01.py
> +gemeinsammeElemente = set(first_list) & set(second_list)
for future projects: consider using english names for your variables

2024-10-28 13:00 UTC, merged