LinusLausberg/Exercise02
dhbw-ma-ppp/ppp-2024 pull request #16
Opened 2024-10-18 15:43 UTC by LinusL2005

2024-10-18 18:15 UTC, PixelWelt approved these changes
The Code works as needed, but can bei improved as mentioned in the comments

2024-10-18 18:15 UTC, PixelWelt commented on Exercises/exercises_02.py
> +print()
Use \n at the end of a Print Statement for a new Line or the end="\n \n" Argument

2024-10-18 18:15 UTC, PixelWelt commented on Exercises/exercises_02.py
> +print('Test der Testreihe 1. Es sollen folgende Zahlen ausgebenwerden: 1, 0, 15, 2.0. Insgesamt 4 Zahlen')
Take a Look into pytest for writing Test cases, that can bei automated.

2024-10-18 18:15 UTC, PixelWelt commented on Exercises/exercises_02.py
> +working_list = commands
I would Put this logic into a function

2024-10-19 10:13 UTC, PixelWelt requested changes

2024-10-19 10:13 UTC, PixelWelt commented on Exercises/exercises_02.py
> +def sorting(input_list):
we should use args as input

2024-10-19 11:33 UTC, LinusL2005 commented on Exercises/exercises_02.py
> +print('Test der Testreihe 1. Es sollen folgende Zahlen ausgebenwerden: 1, 0, 15, 2.0. Insgesamt 4 Zahlen')
ja das hab ich auch überlegt, weil ich das letzte Woche schon ziemlich cool fand. Steht auf der to-Do Liste

2024-10-29 08:28 UTC, PixelWelt commented on Exercises/LinusLausberg/exercies_02
> +def sorting(*starting_list):
nice use of args

2024-10-29 16:06 UTC, PixelWelt commented on Exercises/LinusLausberg/exercies_02
please add the .py extension to your file

2024-10-29 16:07 UTC, atrejut requested changes
please leave the template in place :)

2024-11-04 17:05 UTC, atrejut approved these changes
thanks, changing only the correct file now :)

2024-11-04 19:32 UTC, merged