Finished Excercises01
dhbw-ma-ppp/ppp-2024 pull request #2
Opened 2024-10-15 11:14 UTC by JaeWoo-Westside

2024-10-15 15:04 UTC, PixelWelt commented on Exercises/KevinSiess/excercises_01
> +print("There are ", open_bracket, " more open brackets than closed brackets.")
Schön, dass hier ein Antwortsatz herauskommt. Auch hier fände ich einen f string schöner.

2024-10-15 15:34 UTC, JaeWoo-Westside commented on Exercises/KevinSiess/excercises_01
> +print("Remainder:", remainder)
f' hab ich in deinem code gesehen, aber kein plan was das macht

2024-10-16 07:03 UTC, PixelWelt requested changes
Please upload just one file

2024-10-16 13:13 UTC, PixelWelt commented on Exercises/KevinSiess/excercises_01
> +print("Remainder:", remainder)
Du kannst mit f'{Variablenname}' Variablen inline in deinen Code "reinformatieren". Das ist am Ende besser lesbar

2024-10-25 08:20 UTC, laraasphh approved these changes
Very good!

2024-10-25 09:00 UTC, PixelWelt approved these changes
Working and Just one File! Very good

2024-10-25 09:02 UTC, merged