Exercise_02
dhbw-ma-ppp/ppp-2024 pull request #20
Opened 2024-10-21 17:02 UTC by laraasphh

2024-10-24 10:04 UTC, itsNerdyBirdy approved these changes
Allgemein gut gemacht, ich hatte lediglich ein paar Ideen für Schönheitskorrekturen.

2024-10-24 10:04 UTC, itsNerdyBirdy commented on Exercises/exercises_02.py
> +test1 = sortingLists("1", "ab", "3", "14", "ki", "2.0")
Dein Code fängt es nicht ab, daher meine Frage: Würdest du sagen "one" (bzw. "eins") kann man nicht als Zahl interpretieren?

2024-10-24 18:46 UTC, laraasphh commented on Exercises/exercises_02.py
> +test1 = sortingLists("1", "ab", "3", "14", "ki", "2.0")
Ich hab mich in meinem Code ausschließlich auf Ziffern fokussiert und Zahlwörter außen vor gelassen. Finde deine Frage berechtigt, aber in dem Fall hier interpretiere ich "one" nicht als Zahl, sondern ausschließlich in Form einer Ziffer also dann "1".

2024-10-25 15:56 UTC, atrejut commented on Exercises/exercises_02.py
> +    print(f'The list of all strings which can be interpreted as a number is the following: {listOfNumbers}\n')
The instructions ask for a function that `returns` two lists. Your function prints, but does not return them.

2024-10-25 15:56 UTC, atrejut commented on Exercises/exercises_02.py
> +test3 = sortingLists("abcde", "Python", "99999", "o", "4", "9.99999", "-8.929807317", "b", "0")
For the 'verify' part of the exercise it would be good to see some code that compares actual to expected output (and maybe throws an error if the output does not match the expectation).
In this case you're assigning to three variables here (`test1`, `test2`, `test3`) but the result stored in those variables will be `None` as mentioned above...

2024-10-25 15:56 UTC, atrejut commented on Exercises/exercises_02.py
> +            float(element)
trying to cast is indeed a very good way of testing whether the argument can be interpreted as a number.

2024-10-25 15:58 UTC, atrejut requested changes
just noticed: You're changing the template. Please make sure to create a copy of the file in your own subfolder and only change that.

2024-11-08 12:40 UTC, atrejut approved these changes
thanks, template looks good now

2024-11-08 16:55 UTC, merged