Finished_Excercise02
dhbw-ma-ppp/ppp-2024 pull request #21
Opened 2024-10-22 09:21 UTC by JaeWoo-Westside

2024-10-24 15:13 UTC, laraasphh approved these changes

2024-10-24 15:13 UTC, laraasphh commented on Kevin Siess/KevinSiess_exercises_02.py
> +result = intcode_process([1, 12, 2, 3, 1, 1, 2, 3, 1, 3, 4, 3, 1, 5, 0, 3, 2, 1, 9, 19, 1, 5, 19, 23, 1, 6, 23, 27, 1, 27, 10, 31, 1, 31, 5, 35, 2, 10, 35, 39, 1, 9, 39, 43, 1, 43, 5, 47, 1, 47, 6, 5
Instead of passing your entire list again, you can simply pass the "commands" variable that contains your list to execute your function.

2024-10-24 15:13 UTC, laraasphh commented on Kevin Siess/KevinSiess_exercises_02.py
> +            raise ValueError(f"Ungültiger Opcode {opcode} an Position {pointer} gefunden")
Great idea to also introduce an alternative output in case a certain list element that is not defined as an opcode appears.

2024-10-24 15:13 UTC, laraasphh commented on Kevin Siess/KevinSiess_exercises_02.py
> +        elif opcode == 2:  # *-operation
I like that you included comments in your code so that people can understand the individual operations in your function!

2024-10-24 16:42 UTC, JaeWoo-Westside commented on Kevin Siess/KevinSiess_exercises_02.py
> +            numbers.append(arg)
Warum schreibst du auf English?

2024-10-24 16:42 UTC, JaeWoo-Westside commented on Kevin Siess/KevinSiess_exercises_02.py
> +print(result)
True

2024-10-24 18:03 UTC, laraasphh commented on Kevin Siess/KevinSiess_exercises_02.py
> +            numbers.append(arg)
🤣

2024-10-25 16:18 UTC, atrejut requested changes
- you are deleting the exercise template in your PR. please don't :)
- Please add your folder as a subfolder under `Exercises`, not on the root level of the repository

2024-10-25 16:18 UTC, atrejut commented on Kevin Siess/KevinSiess_exercises_02.py
> +            pos1 = memory[pointer + 1]
you might want to think about ways to re-use code here. A lot of the code in the `1`- and `2`-branch of the if clause is identical currently.

2024-10-25 16:18 UTC, atrejut commented on Kevin Siess/KevinSiess_exercises_02.py
> +def strings_category(*args):
`strings_category` sounds like it /is/ something (a category)
I'd prefer a name that makes it clear that the function /does/ something e.g. `categorize_strings`

2024-10-25 16:18 UTC, atrejut commented on Kevin Siess/KevinSiess_exercises_02.py
> +            single_chars.append(arg)
so a string like '3' only appears in your `numbers`-list but not your `single_chars` list. Was that a conscious decision?

2024-10-25 16:18 UTC, atrejut commented on Kevin Siess/KevinSiess_exercises_02.py
> +result = strings_category("12", "jesus", "19", "z", "hello", "9", "X", "Pokemon")
It would be good to have some code for the 'verify' part that actually compares your output to your expectation and makes sure the two agree

2024-10-26 19:38 UTC, JaeWoo-Westside commented on Kevin Siess/KevinSiess_exercises_02.py
> +            single_chars.append(arg)
Actually yes, at least that's how i understood the assignment.

2024-10-27 08:21 UTC, atrejut commented on Kevin Siess/KevinSiess_exercises_02.py
> +            single_chars.append(arg)
I think the instructions are (somewhat) ambiguous. So the point is to notice the ambiguity and make a conscious decision. I'm fine with either solution to the exercise as long as you noticed the ambiguity :)

2024-10-27 08:21 UTC, atrejut approved these changes
thanks for fixing the file-name issues!

2024-10-27 11:46 UTC, merged