Justus Exercise_02.py
dhbw-ma-ppp/ppp-2024 pull request #25
Opened 2024-10-24 14:38 UTC by Saiki77

2024-10-25 16:21 UTC, atrejut requested changes
you're modifying the exercise template. Please make a copy in your own subfolder instead

2024-10-25 16:21 UTC, atrejut commented on Exercises/exercises_02.py
> +            if arg.startswith(("0x", "-0x")):
nice :D

2024-10-25 16:21 UTC, atrejut commented on Exercises/exercises_02.py
> +            # Opcode 2: multiplication
some duplicate code here between the two functional if-branches. You could try to think of a way to reduce the duplication

2024-10-28 15:51 UTC, FabianPerl93 reviewed
I like your code and the test cases you used. In my opinion, some of the comments were a bit unnecessary, but that's just personal taste.

2024-10-28 15:51 UTC, FabianPerl93 commented on Exercises/exercises_02.py
> +            raise ValueError(f"Unexpected opcode {opcode} at position {pos}")
I really like your idea of implementing an error message, that gives back information about what went wrong.

2024-10-28 15:52 UTC, FabianPerl93 commented on Exercises/exercises_02.py
> +                # Converting hex to integer and append to numbers
I like the idea of additionally checking for hexadecimal numbers.

2024-10-29 07:54 UTC, atrejut approved these changes
thanks for fixing the file issues

2024-10-29 16:20 UTC, merged