finished Exercise 03. My solution is 1306
dhbw-ma-ppp/ppp-2024 pull request #28
Opened 2024-10-26 16:32 UTC by PixelWelt

2024-10-31 15:37 UTC, PhilippSchoeneberg requested changes
Fantastic job here. Just have a look at my comment about the range we had to investigate in the last exercise. It's the only change I request.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +class Card():
I like that you created an extra class for the cards. Like this, it's really organized and could be used pretty good for further implementations of different types of card decks.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +        self.cards = [Card(rank, suit) for suit in Card.SUITS for rank in Card.RANKS]
Nice implementation of the creation of each card without the use of any library.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +    def __init__(self, rank, suit) -> None:
I think you don't need to specify the return parameters in those dunder methods. Especially since you didn't do that in the following classes.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +def test_skat():
Well done testing so many different parameters. I especially like the idea of testing the length.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +
You could've added a test here too. Maybe try using the given examples for those tests.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +def validate_number_range(low, high):
Maybe add a function description with a docstring.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +        number_dict = {}
I really like your implementation of this function using a dictionary, that's a great idea.

2024-10-31 15:37 UTC, PhilippSchoeneberg commented on Exercises/SoerenHerrmann/exercises_03.py
> +    for number in range(low, high+1):
We are supposed to investigate a range of numbers, excluding the upper bound, so I think you should erase the plus one here.

2024-11-03 22:11 UTC, PhilippSchoeneberg approved these changes

2024-11-04 20:34 UTC, atrejut reviewed
Excellent job on the Card Decks (modulo one bug I noticed).
Some very minor suggestions for the number filter, but good work overall

2024-11-04 20:34 UTC, atrejut commented on Exercises/SoerenHerrmann/exercises_03.py
> +        if(rank not in Card.RANKS and suit not in Card.SUITS):
this should be an `or` I think!
Also, PEP-8 says loose the brackets around the if-clause :)

2024-11-04 20:34 UTC, atrejut commented on Exercises/SoerenHerrmann/exercises_03.py
> +        return f"{self.rank} of {self.suit}"
:+1:

2024-11-04 20:34 UTC, atrejut commented on Exercises/SoerenHerrmann/exercises_03.py
> +class FrenchDeck():
Looks great!
You could look into inheriting from `UserList` -- if you store your cards right you don't even need to implement the dunder methods yourself then -- but for the exercise the way you did this is pretty much perfect...

2024-11-04 20:34 UTC, atrejut commented on Exercises/SoerenHerrmann/exercises_03.py
> +        if list(num_str) == sorted(num_str):
I think doing something like
```
if list(num_str) != sorted(num_str):
    continue
```
and then skipping the indentation for the other check would be more readable. Or you refactor the two check into their own methods

2024-11-04 20:34 UTC, atrejut commented on Exercises/SoerenHerrmann/exercises_03.py
> +                if num_str[i] == num_str[i + 1]:
the dict-approach is nice. It can be simplified to 
```
number_dict[num_str[i]] = number_dict.get(num_str[i], 0) + 1
```
without any `if`-clauses.
Alternatively look into `defaultdict` from the `collections` library

Also, you're using `num_str[i]` so often in this loop that it woud be nice to give it a real variable :)

2024-11-06 18:05 UTC, merged