Kevin Siess_ Abgabe_03_(resulting count: 1306)
dhbw-ma-ppp/ppp-2024 pull request #29
Opened 2024-10-27 09:47 UTC by JaeWoo-Westside

2024-10-28 21:03 UTC, PixelWelt requested changes
please remove exercise 1 from PR
A french deck has 52 cards

All the other changes or ideas are optional and not needed for an approval

2024-10-28 21:03 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +    def has_exactly_two_adjacent_matching_digits(number):
what is the benefit of defining the function in the inner scope?

2024-10-28 21:03 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +        for i in range(1, len(number_str)):
you could copy your number_str and sort it. After that you can just make one test if the two are equal

2024-10-28 21:03 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +print("Count of valid numbers:", result)
f strings could've been used here

2024-10-28 21:08 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +class Skatdeck:
you could makr Skatdeck inherit from frenchdeck to write less code with the same function

2024-10-29 16:08 UTC, JaeWoo-Westside commented on Exercises/KevinSiess/KevinSiess_exercises_01.py
changed the name and the previous vile is in the wrong folder

2024-10-31 09:53 UTC, PixelWelt approved these changes
nice work

2024-10-31 09:53 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +print(f"\nTesting Skatdeck:")
why are you adding f without printing a variable. in this case the f is obsolete

2024-10-31 09:53 UTC, PixelWelt commented on Exercises/KevinSiess/KevinSiess_exercises_03.py
> +print(f"Count of valid numbers: {result}")
nice

2024-11-17 19:52 UTC, merged