Adrian Erdmann Abgabe 01
dhbw-ma-ppp/ppp-2024 pull request #7
Opened 2024-10-15 15:29 UTC by Adrian410

2024-10-19 14:01 UTC, PhilippSchoeneberg approved these changes
Well done!

2024-10-19 14:01 UTC, PhilippSchoeneberg commented on Exercises/AdrianErdmann/excercise_01AE.py
> +common_elements = first_list and second_list
Nice usage of the learned and operator.

2024-10-19 14:01 UTC, PhilippSchoeneberg commented on Exercises/AdrianErdmann/excercise_01AE.py
> +print(f"The result of the integer division of 2711274328912 / 23369245575 is: {2711274328912 // 23369245575} and the remainder after the integer devision is: {2711274328912 % 23369245575}\n")
I like that you are always using f-strings.

2024-10-19 14:52 UTC, itsNerdyBirdy requested changes
Bitte füge die von mir gewünschten Kommentare hinzu, alles andere kannst du ignorieren wenn du magst.

2024-10-19 14:52 UTC, itsNerdyBirdy commented on Exercises/AdrianErdmann/excercise_01AE.py
> +print(f"there are {input_string.count("(") - input_string.count(")")}more ( than ).\n")
Auch hier könnte dein f-String lesbarer sein, wenn du die Rechnungen außerhalb des Prints in einer eigenen Variablen speicherst.

2024-10-19 14:52 UTC, itsNerdyBirdy commented on Exercises/AdrianErdmann/excercise_01AE.py
> +print(f"The first list contains {len(first_list)} elments and the second list consists out of {len(second_list)} elements.\n")
Siehe Kommentar f-String für Zeile 17.

2024-10-19 14:52 UTC, itsNerdyBirdy commented on Exercises/AdrianErdmann/excercise_01AE.py
> +common_elements = first_list and second_list
Ein Kommentar, zum Zweck dieser Zeile würde die Verständlichkeit steigern.

2024-10-19 14:52 UTC, itsNerdyBirdy commented on Exercises/AdrianErdmann/excercise_01AE.py
> +print(f"There are {len(common_elements)} elements common to both lists, with the elements beeing: {", ".join(common_elements)}.\n")
Siehe Kommentar f-Strings für Zeile 17

2024-10-19 14:52 UTC, itsNerdyBirdy commented on Exercises/AdrianErdmann/excercise_01AE.py
> +print(f"There are {str(first_list).count("a")} a's in the first and {str(second_list).count("a")} a's in the second list.\n")
Siehe Kommentar f-String für Zeile 17

Ein Kommentar, welcher erläutert, was du mit "str(first_line).count("a") bezweckst und welcher der zu erwartende Datentyp ist, würde beim Verständnis des Prints helfen.

2024-10-25 15:42 UTC, atrejut commented
@Adrian410 Please merge this PR

2024-10-25 16:04 UTC, merged