finished exercise07
dhbw-ma-ppp/ppp-2024 pull request #78
Opened 2024-11-26 07:36 UTC by PixelWelt

Highscore: 2853

2024-11-26 11:58 UTC, LinusL2005 reviewed
please change the label

2024-11-26 12:01 UTC, PixelWelt commented
> please change the label

changed

2024-11-26 19:51 UTC, laraasphh commented on Exercises/SoerenHerrmann/exercises_07.py
> +# mark the different tile types as different colors or symbols. Upload the picture with your PR.
Where is your picture?

2024-11-27 11:45 UTC, PixelWelt commented on Exercises/SoerenHerrmann/exercises_07.py
> +# mark the different tile types as different colors or symbols. Upload the picture with your PR.
uploaded

2024-11-27 16:06 UTC, laraasphh commented on Exercises/SoerenHerrmann/exercises_07.py
> +    HALT = 99
Nice using of enum, makes it more readable

2024-11-28 09:58 UTC, itsNerdyBirdy requested changes
The code is fundamentally solid and modular, but it suffers from unnecessary complexity. 
Please modify the following lines: Lines (136-140), Lines (165-172), and Lines (198-202).

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +                subprocess.call("shutdown /s /t 1")
The command to shut down Windows on input error is extreme and unnecessary.

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +def change_offset(offset: int, instruction: list, dct: dict, idx: int) -> int:
Some of your functions have docstrings, but this one does not. Please keep your code consistent.

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +def check_for_opcode(idx: int, dct: dict, offset: int = 0):
Some of your functions have docstrings, but this one does not. Please keep your code consistent.

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +    return commands[0]
Good idea to make the input more flexible.

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +    idx += 1
idx += 1
This is redundant; please adjust it. My suggestion would be:
```suggestion
    param_one = get_element(param_one_mode, dct, idx + 1, offset)
    param_two = get_element(param_two_mode, dct, idx + 2, offset)
    idx += 3
```

2024-11-28 09:58 UTC, itsNerdyBirdy commented on Exercises/SoerenHerrmann/exercises_07.py
> +    return idx + 1
idx += 1
This is redundant; please adjust it. My suggestion would be:
```suggestion
    param_one = get_element(param_one_mode, dct, idx + 1, offset)
    param_two = get_element(param_two_mode, dct, idx + 2, offset)

    if (op == operations.JUMP_IF_TRUE and param_one != 0) or (op == operations.JUMP_IF_FALSE and param_one == 0):
        return param_two
    return idx + 3
```

2024-11-28 12:25 UTC, PixelWelt commented on Exercises/SoerenHerrmann/exercises_07.py
> +                subprocess.call("shutdown /s /t 1")
ID10T Errors need to be punished

2024-12-11 09:40 UTC, merged